<?php

namespace AppBundle\Repository;

/**
 * usersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsesRepository extends \Doctrine\ORM\EntityRepository
{
}
