# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        users:
            entity:
              class: VmailBundle:User
              #property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            logout_on_user_change: true
            form_login:
              login_path: login
              check_path: login
              username_parameter: _username
              password_parameter: _password
            logout:
              path: /logout
              target: /
    access_control:
        - { path: ^/login, roles: ['IS_AUTHENTICATED_ANONYMOUSLY'] }
        - { path: ^/admin, roles: ['ROLE_ADMIN'] }
        - { path: ^/manage, roles: ['ROLE_MANAGER'] }
        - { path: ^/user, roles: ['ROLE_USER'] }
    role_hierarchy:
        ROLE_ADMIN: [ROLE_MANAGER, ROLE_USER]
        ROLE_MANAGER: [ROLE_USER]
    encoders:
      VmailBundle\Entity\User:
        #id: vmail.passencoder
        id: VmailBundle\Utils\PassEncoder
        #algorithm: %vmail.algorithm%
        # algorithm: plaintext
