# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    vmail.config:
      class: VmailBundle\Utils\ReadConfig
      arguments: ['@doctrine.orm.entity_manager']

    vmail.deliver:
      class: VmailBundle\Utils\DeliverMail
      arguments: ['@doctrine.orm.entity_manager']

    vmail.passencoder:
      class: VmailBundle\Utils\PassEncoder
      
