# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    vmail.config:
      class: VmailBundle\Utils\ReadConfig
      #arguments: ['@doctrine.orm.entity_manager']
      properties:
        em: '@doctrine.orm.entity_manager'

    vmail.deliver:
      class: VmailBundle\Utils\DeliverMail
      properties:
        mailer: '@mailer'

    vmail.autoreply:
      class: VmailBundle\VmailBundle\Utils\AutoreplyMail
      arguments: ['@doctrine.orm.entity_manager']
      properties:
        deliver: '@vmail.deliver'
        config: '@vmail.config'

    vmail.passencoder:
      class: VmailBundle\Utils\PassEncoder
