#!/bin/sh
#PHPRC="/etc/php7.0/cgi/"
#export PHPRC
VMAIL_HOME="/home/vmail/vmail"
PHP_DOCUMENT_ROOT="$VMAIL_HOME/web"
export PHP_DOCUMENT_ROOT
# The variable PHP_FCGI_CHILDREN is onyl useful for lighty or nginx as apache
# mod_fcgi will control the number of childs themself and never use the additional processes.
# PHP_FCGI_CHILDREN=8
# export PHP_FCGI_CHILDREN
PHP_FCGI_MAX_REQUESTS=5000
export PHP_FCGI_MAX_REQUESTS
exec /usr/bin/php-cgi \
 -d open_basedir="${PHP_DOCUMENT_ROOT}:/tmp:/dev" \
 -d session.save_path=$VMAIL_HOME/var/sessions \
 $1
